### ISSUE TITLE
Porting 0CC-Famitracker to Qt (using Nesicide)

### ISSUE THREAD

**Issue by nyanpasu64** [christopherpow/nesicide#29]
I'm trying to build 0CC on Android.

Building 0CC for ARM using Visual Studio failed because there's no prebuilt MFCxxxx.lib for ARM, and mfc110.dll can be converted into a .lib (but MSVC++11 is too old for 0CC).

Building 0CC for ARM using Winelib failed because I can't build MFC in Winelib.

I built Nesicide-Famitracker on a Raspberry Pi using updated Wine headers (you must compile Wine to convert .idl to .h) and QT 5.7 or something.

Now I'm trying to add an Android target using QT Creator and latest QT 5.10 on Windows...

I tried compiling for Windows in QT Creator, using MSVC++15 (2017) instead of MinGW, but it complains hundreds of times about TCHAR*=_T("asdf") and TCHAR=_T('c') since the RHS is const (I couldn't figure out how to replace _T with an unconst cast). Maybe 0CC 0.3.14.5 is a good idea? Also I like MinGW-w64 or msys2 over mingw.

Now I'm trying to use QT Creator and NDK 10e (QT requires an old NDK version) gcc to compile for Android. I just moved over the Wine headers from Pi to my Windows laptop, and will be trying to setup and build over the next few days. Maybe I'll throw in 0CC instead of FT. How difficult would adapting 0CC to Qt be?

**Comment by christopherpow** [comment]
I took a brief look at 0CC and found it to be more complicated of a migration into the existing Qt Famitracker than I'd hoped. I haven't made much progress on it. There's quite a departure in styles and language capability usage between the two versions.

**Comment by jimbo1qaz** [comment]
0CC 0.3.14.5 or jimbo1qaz/0CC-Famitracker should have an older codebase. I was trying to port to Android, but had trouble compiling https://github.com/pelya/commandergenius on Windows (SDL 1.2 port to Android). I researched Qt or Android audio libraries, but stopped working (gave up) on the port.

SDL 2.0 has an official port, and HertzDevil mentioned on Famitracker discord, that he was experimenting with 0CC and SDL.

**Comment by jimbo1qaz** [comment]
i'm trying to document your exact changes from 0.4.6 at https://docs.google.com/document/d/1jLTmbk_hjBHMOUzrLjfe5m_-ZyKg7LmbBeHxD3MjBg8/edit, which should help me incorporate those changes into 0CC. Not quite done yet.

seems you're using outdated versions of emu2149 and emu2413, relative to 0.4.6 https://github.com/Camano/FamiTracker.

**Comment by christopherpow** [comment]
Interesting. Perhaps the emu2149 and emu2413 files got dropped somewhere along the migration from 0.4.1 to 0.4.6. Looks like a pretty comprehensive list of file differences. I'd tried to make it as minimally invasive as possible for the original FT code. Not sure if you got that sense from your review?

**Comment by jimbo1qaz** [comment]
This actually isn't the *complete* list of changes...

There were a large number of style changes... So I threw both projects through clang-format... And removed all empty lines... (which made `diff -r` think the entire file was a block, so I added empty lines *everywhere* ;) ).

oof... I spent hours normalizing the case of .cpp files, header files, and #include statements, when I could've just used `diff -i` to ignore those changes. For that matter, `man diff` reveals a smorgasbord of whitespace-dropping options I forgot to use.

You removed all occurrences of `ON_EVENT(something, &CClass::Something)` and one occurrence of `ON_EVENT(something, CClass::Something)`, why was that? Did the compatibility layer not support that well? In any case, I have a fork of 0.4.6 and j0CC with the same change applied, to reduce unimportant diffs.

I accidentally corrupted my "source code folder" by adding blank lines everywhere while trying to simplify diffs. And somehow Git generated N163.h and N163.H in the same folder. On Windows. On a case-insensitive system (except Windows Ubuntu is kinda-sorta case sensitive).

**Comment by christopherpow** [comment]
The compatibility layer shit itself whenever it came across ON_EVENT(something, &CClass::Something), specifically the scope portion (CClass::). I couldn't figure out why and since there were only a few instances where the scope-specifier was present I just removed them. It'd be nice to figure that out so I wouldn't have to touch the message maps AT ALL. In my many-moons-ago implementation I'd attempted to replace the message map architecture with signal/slot, but that led me down a path of waaaay too much context-specific glue code, which I'd set out to avoid at all costs.

diff is a fantastic tool! :)

**Comment by jimbo1qaz** [comment]
I noticed you removed or omiited `#include <algorithm>` in several files, even though APU.cpp used std::min and std::max. Is that intentional or not?

**Comment by jimbo1qaz** [comment]
I think i've hit a roadblock. `cqtmfc_famitracker.cpp` appears to be a translation of `FamiTracker.rc`, but they don't match exactly. Was that done programmatically or by hand (all 244 KB typed, one line at a time?)

**Comment by christopherpow** [comment]
Originally the compile failed because of missing <algorithm>. When I removed it to see if it was even needed and the compile succeeded, well...I left it removed. :)

As for cqtmfc_famitracker.cpp, yes, that was entirely hand coded. I thought about creating a .rc->.moc translator tool but when it came down to the details it was quicker to just manually do it. I'm still interested in the possibility of a .rc->.moc tool, in general as an expansion of the idea that *any* MFC app can be run atop Qt. The file isn't that hard to maintain against .rc file changes now especially with a meld of the old/new .rc files open.

**Comment by christopherpow** [comment]
I meant I hadn't got far enough in the 0CC port (0CC-ft branch, not master) to where I'd even tackled the updates to cqtmfc_famitracker.cpp needed by the changes between 0CC-FamiTracker.rc and FamiTracker.rc. 

For example, there is a control item labeled "Include grooves" in 0CC-FamiTracker.rc. I don't have that in cqtmfc_famitracker.cpp.

I can do the .rc porting, yes.

As for a tool, I misspoke. moc is the signal/slot translator. I meant a tool that translates .rc->.ui files. A .ui file is XML of the UI.

**Comment by jimbo1qaz** [comment]
https://github.com/jimbo1qaz/j0CC-Famitracker-Qt

Only tested on Qt Creator, MSVC, Windows. qmake works, but compilation crashes and burns (one reason is because cqtmfc_famitracker.cpp).

(Also many source files seem to omit `\<algorithm\>` (thanks markdown), MFC headers and class definitions, but still compile in Visual Studio. They don't compile in Qt Creator unfortunately. Why is that?)

**Comment by christopherpow** [comment]
By the way, cqtmfc.cpp/.h are also 'glue'.

**Comment by jimbo1qaz** [comment]
so i tried compiling the original nesicide in Qt Creator (with latest Qt 5.10.1) (not using shell scripts)... after a pile of pain (turns out you should open `build\famitracker\famitracker.pro` (and no other projects) in qt creator, and msvc doesn't work)... slow compilation with make, and errors with jom... Finally finished building.

I get dll errors when opening famitracker.exe in Windows Explorer. and 0xc0000139 when launching from Qt Creator.

Qt Installer: "MinGW 5.3.0 32 bit" Qt library, and "MinGW 5.3.0" toolchain from MinGW-builds. Compiler should be compatible, Qt Creator doesn't complain that Qt doesn't match the compiler, but the app won't launch.

http://www.qtcentre.org/threads/53617-Qt-5-0-1-MinGW-programs-does-not-launch-exited-with-code-0xc0000139?p=240227#post240227 ?????

I'll try downgrading to ~~5.6.2~~ 5.6.3 was found in the online Qt installer, and 5.6.2 added an old version of Qt creator I didn't use... 5.6.3 also has same issue.

**Comment by jimbo1qaz** [comment]
are you trying to build my new repo? It doesn't build for me, even.

I have some questions, In Qt Creator, if I don't open the subprojects, I get this, and Ctrl+K doesn't "see" any of the embedded files. 
![image](https://user-images.githubusercontent.com/913957/39973171-60f27c6e-56d1-11e8-8c06-2d311939e3f0.png)

If I open the subprojects, I get this, and every project has its own build configuration. Is that normal?
![image](https://user-images.githubusercontent.com/913957/39973264-a2c96656-56d2-11e8-87b7-5090798f775e.png)

**Comment by jimbo1qaz** [comment]
Trying to compile with MSVC. qmake insists on passing -Zc:strictStrings and nothing I do (removing flag, removing flag from debug, clearing all flags entirely) will convince it otherwise. I tried deleting all .qmake.stash files to no success.
![image](https://user-images.githubusercontent.com/913957/39973385-3dc5e48a-56d4-11e8-8e75-f539440cc9f0.png)

**Comment by christopherpow** [comment]
The Qt not showing subproject content thing is an issue I've seen but it generally clears up after a while -- like it's syncing the project in the background. I'm not a keyboard shortcut guy so I have no idea what Ctrl+K and Ctrl+Shift+B are supposed to do.

You're supposed to open the .pro files in nesicide/build/. Those are subdirs .pro files which 'contain' all of the subprojects required to build the whole project. So famitracker.pro contains all of the projects for famitracker. ide.pro contains all of the projects for nesicide, etc. You can build the whole thing by building at the top level, or build individual subprojects by building from their level. That is how I've been doing the Qt/0CC merge thus far -- just rebuilding the famitracker-lib project, since the famitracker(-app) project is irrelevant until the -lib project compiles.

I can't bother with MSVC I don't have a working Qt installation in Windows that I have regular access to at the moment. I'm either using MinGW in a Windows machine I have occasional (read: lunch breaks at work) access to, or clang on my MacBook.

No, I haven't tried to build your new repo, I was just curious if you'd been able to get past that issue. It seems it might be a clang issue, so you might not see it.

**Comment by jimbo1qaz** [comment]
(Using MSVC) Seems some functions in cqtmfc.cpp cause linking conflicts with the real windows.h.

```
kernel32.lib(KERNEL32.dll) : error LNK2005: CloseHandle already defined in cqtmfc.obj
kernel32.lib(KERNEL32.dll) : error LNK2005: SetEvent already defined in cqtmfc.obj
kernel32.lib(KERNEL32.dll) : error LNK2005: ResetEvent already defined in cqtmfc.obj
```

If I remove those functions from the .cpp file, it compiles...

CVisualizerWnd::FlushSamples(...) calls Windows's `SetEvent(m_hNewSamples)`. The value is around 0x300.

CVisualizerWnd::ThreadProc() calls cqtmfc's `WaitForSingleObject(hHandle=m_hNewSamples, dwMilliseconds=INFINITE)`.

- CObject* pObject = (CObject*)hHandle;
- CCmdTarget* pCmdTarget = dynamic_cast<CCmdTarget*>(pObject);
  - crashes since hHandle is not a valid pointer.

honestly I think trying to make this MSVC-compatible is a waste of my own time. Should I push some of my partial MSVC fixes?

**Comment by christopherpow** [comment]
I finally got back to this and got past the C++17 issues I was having before. I can now start the resource file conversion. There is a huge pile of differences that will take some time to parse through. It's reinvigorating my desire to create a tool to do it for me.

**Comment by jimbo1qaz** [comment]
I wrote up a "vanilla vs nesicide" diff at https://hackmd.io/@IFuHNFVvQXWfCLfmOaJA1w/S1L_6G71S . My plan is to copy the entire j0cc repo in place of vanilla, regenerate the cqtmfc...cpp, and then port over all changes to vanilla to j0cc.

Git comparison repo (including methodology) is at https://github.com/jimbo1qaz/famitracker-vs-nesicide. Files have been lowercased, line endings converted to Unix, comments and empty lines removed, and clang-format applied.

--------

Why did 883097c6a2096f4f2e601dc83177cd4e87e28d67 change `libs/famitracker/Source/ColorScheme.h` and you extracted `_STATIC_COLOR_SCHEME` from `STATIC_COLOR_SCHEME`? This change is not in vanilla 0.4.6 or j0cc.

https://github.com/christopherpow/nesicide/commit/883097c6a2096f4f2e601dc83177cd4e87e28d67#diff-80b1c26f4f22c9d6a938d0c4f71f8fdeR29 claims to be updating nesicide to vanilla 0.4.2.

Do you have any other means of communication other than issue trackers, or is this thread OK?

**Comment by jimbo1qaz** [comment]
Why does https://github.com/christopherpow/nesicide/blob/master/libs/famitracker/Source/stdafx.h include `#include "cqtmfc.h"` twice?

**Comment by christopherpow** [comment]
Guess that was a typo. Fixed.

**Comment by jimbo1qaz** [comment]
https://github.com/christopherpow/nesicide/blob/master/libs/famitracker/Source/SoundGen.h has `#include "Common.h"` twice.

**Comment by jimbo1qaz** [comment]
I think `CImageList` pushes `new CBitmap` into `_images: QList<CBitmap*>`, but never deletes them. I think this is a memory leak. Maybe you should switch to `unique_ptr` and maybe `make_unique` (c++14).

(I'm implementing `CImageList::Replace(int nImage, CBitmap* pbmImage, CBitmap* pbmMask)` among *many* other things.)

**Comment by christopherpow** [comment]
You're probably right but please keep in mind that missing or unexpected (no deletion/removal) functionality is likely intentional -- I only implemented the bare minimum of what I would need to get the job done. It is by no means a *perfect* MFC emulation. Anything you add to make it better will only do that...make it better. Thanks.

**Comment by jimbo1qaz** [comment]
I'm thinking of starting from scratch and porting j0cc to WxWidgets, which has a similar API to MFC, including a WxImageList.
I think the current code base is seriously flawed and hacky (though possible to somewhat clean up with lots of extra work and investigation). Does CImageList essentially hold void* which can either be CBitmap or QIcon, and the ExtractImage caller hopefully uses the right cast?

**Comment by christopherpow** [comment]
You're free to do whatever you want, of course. I never implied that my Qt emulation is perfect. It has a lot of half/unimplemented functionality *because I didn't need it all*. I'm not sure I follow your trouble with CImageList. It holds a QList<CBitmap*>...
If you want me to implement CImageList::Replace, I can take a look at that. Seems pretty straight forward to me.
If I were being paid to implement a MFC emulation on Qt, that'd be different.

**Comment by christopherpow** [comment]
Can this issue be closed?

**Comment by nyanpasu64** [comment]
I'm no longer working on "0cc to qt", so go ahead.

**Comment by christopherpow** [comment]
Are you working on Occ to WxWidgets? How goes?
