### ISSUE TITLE
Closing IDE while graphics banks are opened destroys project file

### ISSUE THREAD

**Issue by aa-dav** [christopherpow/nesicide#61]
(windows 10, last build)
1. Create new project from template "hello world" (ca65)
2. Open tab with graphics banks
3. Close IDE - if asks "save changes?" - press "Yes".
Result: Hello world.nesproject is empty.

**Comment by christopherpow** [comment]
I am unable to reproduce this in https://bintray.com/christopherpow/nesicide/nesicide/1.0.107#files

**Comment by christopherpow** [comment]
FWIW I tried both OSX and Windows builds and am unable to reproduce given the steps.

**Comment by aa-dav** [comment]
Hmm....
I reproduce it very easily. I may make video of process.
Maybe content of global IDE settings are important?
I add CSPSoftware/NESICIDE.ini here in attach.
Also my manual settings after archive unpack are:
- uncheck 'Show welcome on startup...."
- Editor/encoding -> utf-8
- Tabs -> 8
- uncheck 'replace Tabs with spaces...'

[NESICIDE.zip](https://github.com/christopherpow/nesicide/files/4270811/NESICIDE.zip)
Projects are created in dir c:\devel\nes\

**Comment by aa-dav** [comment]
Well, this this release https://bintray.com/christopherpow/nesicide/nesicide/1.0.107#files I could not reproduce it too. But it's extremly unstable and even crashes while opening my example project from latest version. Well, it's strange. I'll monitor future versions.

**Comment by christopherpow** [comment]
I have been seeing crashes on project opening occasionally. I am not yet sure of the cause.

**Comment by christopherpow** [comment]
RE the crashes can you try with https://bintray.com/christopherpow/nesicide/nesicide/1.0.109#files
And also let me know if it crashes when you're already running a ROM in the emulator, or if the emulator is paused, or both? I think it's caused by some inappropriate threading behavior when a project is being shut down.

**Comment by aa-dav** [comment]
> https://bintray.com/christopherpow/nesicide/nesicide/1.0.109#files
My steps:
1. download, unpack, run
2. goto preferences: uncheck 'show welcome', set utf-8, tabs=8, uncheck 'replace by spaces'
3. open project c:\devel\nes\Example03 (I add it in attach)
CRASH (IDE just dissapears)
4. run it again and open project again
For 1 second I see project tree, but then IDE shuts down like I close it myself.
[Example04.zip](https://github.com/christopherpow/nesicide/files/4273361/Example04.zip)

**Comment by christopherpow** [comment]
@aa-dav latest build https://knob.phreneticappsllc.com/nesicide/?s=download seems pretty stable on Windows. Let me know. Also, your Example04 project seems to have double-newlines, which appears to throw off the execution-line marking. I'm not sure if that's caused by the project wizard creating the project or when it's saved as utf8.
